[build.environment]
  YARN_VERSION = "1.19.0"
  NPM_VERSION = "6.11.3"
  HUGO_VERSION = "0.58.3"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"
